# Generated by Django 5.2 on 2025-04-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('on_revision', 'На доработке'), ('completed', 'Выполнена'), ('archived', 'В архиве')], default='in_progress', max_length=20),
        ),
    ]
