# Generated by Django 5.2 on 2025-05-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
    ]
